defmodule BuscaLivro.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_pedidos, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_pedidos_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :pedido_id, :uuid, null: false
    end

    create table(:pedidos, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:user_pedidos) do
      modify :pedido_id,
             references(:pedidos,
               column: :id,
               name: "user_pedidos_pedido_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:pedidos) do
      add :texto, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:lojas, primary_key: false) do
      add :nome, :text, null: false, primary_key: true
      add :url, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:lojas, [:nome], name: "lojas_unique_nome_index")

    create table(:livros, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :titulo, :text, null: false
      add :image_url, :text
      add :descricao, :text
      add :preco, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :loja_nome,
          references(:lojas,
            column: :nome,
            name: "livros_loja_nome_fkey",
            type: :text,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:livros, "livros_loja_nome_fkey")

    drop table(:livros)

    drop_if_exists unique_index(:lojas, [:nome], name: "lojas_unique_nome_index")

    drop table(:lojas)

    alter table(:pedidos) do
      remove :updated_at
      remove :inserted_at
      remove :texto
    end

    drop constraint(:user_pedidos, "user_pedidos_pedido_id_fkey")

    alter table(:user_pedidos) do
      modify :pedido_id, :uuid
    end

    drop table(:pedidos)

    drop constraint(:user_pedidos, "user_pedidos_user_id_fkey")

    drop table(:user_pedidos)
  end
end
