defmodule BuscaLivro.Repo.Migrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint("user_pedidos", "user_pedidos_pkey")

    alter table(:user_pedidos) do
      modify :pedido_id, :uuid, primary_key: false
      modify :user_id, :uuid, primary_key: false
    end
  end

  def down do
    alter table(:user_pedidos) do
      modify :user_id, :uuid, primary_key: true
      modify :pedido_id, :uuid, primary_key: true
    end
  end
end
