defmodule BuscaLivro.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:livros) do
      add :descricao, :text
    end
  end

  def down do
    alter table(:livros) do
      remove :descricao
    end
  end
end
