defmodule BuscaLivro.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_pedidos, primary_key: false) do
      add :user_id,
          references(:users,
            column: :id,
            name: "user_pedidos_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), primary_key: true, null: false

      add :pedido_id, :uuid, null: false, primary_key: true
    end

    create table(:pedidos, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:user_pedidos) do
      modify :pedido_id,
             references(:pedidos,
               column: :id,
               name: "user_pedidos_pedido_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:pedidos) do
      add :texto, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:pedidos) do
      remove :updated_at
      remove :inserted_at
      remove :texto
    end

    drop constraint(:user_pedidos, "user_pedidos_pedido_id_fkey")

    alter table(:user_pedidos) do
      modify :pedido_id, :uuid
    end

    drop table(:pedidos)

    drop constraint(:user_pedidos, "user_pedidos_user_id_fkey")

    drop table(:user_pedidos)
  end
end
